---
- name: copy requirements.txt
  copy:
    src: "{{ requirements }}"
    dest: "/home/sdixon/{{ requirements }}"
  tags:
    - deploy
- name: Install pip packages and virtualenv
  pip:
    virtualenv_python: python3
    virtualenv: "/home/sdixon/.venv/sjd.im-venv"
    requirements: "/home/sdixon/{{ requirements }}"
