---
- name: clone sjd.im repo
  become: true
  git:
    repo: "https://github.com/samdixon/sjd.im.git"
    dest: "/sjd.im"
    update: yes

- name: set repo permissions
  become: true
  file:
    path: /sjd.im
    owner: sdixon
    group: sdixon
    mode: '0440'
    recurse: yes

- name: copy nginx conf
  become: true
  copy:
    src: "{{ nginx_conf }}"
    dest: /etc/nginx/sites-enabled/default

- name: restart nginx
  become: true
  service:
    name: nginx
    state: reloaded
