---
- hosts: all

  tasks:
      - name: add user sdixon
        remote_user: root
        become: true
        user:
            name: sdixon
            group: sudo
            state: present
            shell: /bin/bash
      - name: passwordless sudo
        lineinfile:
            path: /etc/sudoers
            state: present
            regexp: '^%sudo'
            line: '%sudo ALL=ALL    NOPASSWD: ALL'
            validate: 'visudo -cf %s'
      - name: make directory
        file:
            path: "/home/sdixon/.ssh"
            state: directory
      - name: create empty file
        file:
            path: "/home/sdixon/.ssh/authorized_keys"
            state: touch
      - name: put pubkey
        lineinfile:
            path: "/home/sdixon/.ssh/authorized_keys"
            line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDE5CKffriYyaUADcDV9N3Zam35USMdBYv84YF3i3/J+iQpoiNM5pJG2LnMjeLoFjbG67ohPiBHt5cWRUt6KdhIuoH6SGTVya1ns7mvykLd5FxpNwcNaChnKQ/JLSfVslb5/HGk1k05xx+hkRAm9WUJeiKVcVnSp4CarwDBHfoWvKPZji4julVpHtJwDfzGLB3SEYnf+upUlnw1/jbM9pTN99M+udjFMVQXhqa31sLwZ2u9IBdgt3ZpG+zm3PmWolbBaQawBcPqu0RenjcFV86rv0x0eTS13JBevftgUuxflfjryrz2gXIvaOjDaGGZt9z2fOEXLflujDgiEdCoCakJwChhCkeN6IH9fZppU5FT6r13ADWDuW3nHvaGSTQH25eyt/ox61czcoMiVOU8xFYwOY23RNcT1Ytbt52GfpK6Azq/MIFqCwAvwc1Eea0B3t4cNTclIdXyodhqYMZmgGJsqbTD1ciY3yi8KqazI/gIwsn4FXgPd9jgQKL9MnoX0wE= sdixon@walkman2"
      

        
