---
- name: Update & Upgrade packages
  become: true
  apt:
    update_cache: yes
    upgrade: yes
  tags:
    - updates
- name: Install webserver packages
  become: true
  apt:
      pkg:
          - curl
          - htop
          - vim
          - python3
          - python3-pip
          - virtualenv
          - nginx
          - git
- name: Enable nginx
  become: true
  service:
    name: nginx
    state: started
    enabled: yes
